services:
  django_app:
    image: sadiyairin/hhm-backend:latest
    container_name: django_app
    restart: always
    expose:
      - "8005"
    env_file: .env
    volumes:
      - ./static:/app/static # জ্যাঙ্গো স্ট্যাটিক ফাইল এখানে জমা করবে
      - ./media:/app/media # ইউজার আপলোড করা ছবি বা ফাইলের জন্য (যদি থাকে)

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./static:/app/static:ro # এনজিনেক্স এখান থেকে অ্যাডমিন সিএসএস পড়বে
      - ./media:/app/media:ro # মিডিয়া ফাইল দেখানোর জন্য
    depends_on:
      - django_app
