# Generated by Django 5.2.7 on 2025-10-29 10:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlugType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("is_fast_charge", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("CAR", "Car"), ("BIKE", "Bike")], max_length=10
                    ),
                ),
                ("battery_type", models.CharField(max_length=50)),
                ("units_per_time", models.CharField(default="kW/h", max_length=50)),
                (
                    "battery_capacity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "charging_time",
                    models.DurationField(default=datetime.timedelta(seconds=14400)),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="vehicle_images/"
                    ),
                ),
                ("supported_plugs", models.ManyToManyField(to="driver.plugtype")),
            ],
        ),
        migrations.CreateModel(
            name="UserVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=20, unique=True)),
                (
                    "units_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "time_value",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                (
                    "selected_plug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="driver.plugtype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="driver.vehicle"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "registration_number")},
            },
        ),
    ]
