# Generated by Django 5.2.6 on 2025-11-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservehicle",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
