# Generated by Django 5.2.6 on 2025-11-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver", "0002_uservehicle_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="plugtype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="plug_types/"),
        ),
    ]
