# Generated by Django 5.2.7 on 2025-10-29 12:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("driver", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChargerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("voltage", models.IntegerField(blank=True, null=True)),
                ("amperage", models.IntegerField(blank=True, null=True)),
                ("is_fast_charge", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ConnectorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChargingStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(max_length=200, verbose_name="Station Name"),
                ),
                (
                    "location_area",
                    models.CharField(
                        max_length=255, verbose_name="Location Area/Expressway"
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OP", "Open"),
                            ("CL", "Closed"),
                            ("MA", "In Maintenance"),
                        ],
                        default="OP",
                        max_length=2,
                    ),
                ),
                ("opening_time", models.TimeField(default=datetime.time(9, 0))),
                ("closing_time", models.TimeField(default=datetime.time(22, 0))),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "google_place_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="station_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charging_station",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Charging Station",
                "verbose_name_plural": "Charging Stations",
                "ordering": ["station_name"],
            },
        ),
        migrations.CreateModel(
            name="Charger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "scanner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="charger_scanners/"
                    ),
                ),
                (
                    "extended_time_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="Extra hours or kWh unit",
                        max_digits=5,
                    ),
                ),
                (
                    "extended_price_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Charge per extended unit",
                        max_digits=6,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("hour", "Per Hour"), ("kwh", "Per kWh")],
                        default="hour",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("available", models.BooleanField(default=True)),
                ("open_24_7", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "plug_types",
                    models.ManyToManyField(
                        related_name="chargers", to="driver.plugtype"
                    ),
                ),
                (
                    "charger_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chargers",
                        to="host.chargertype",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chargers",
                        to="host.chargingstation",
                    ),
                ),
                (
                    "connector_types",
                    models.ManyToManyField(
                        related_name="chargers", to="host.connectortype"
                    ),
                ),
            ],
        ),
    ]
