# Generated by Django 5.2.7 on 2025-10-30 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="scanner_code",
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
