# Generated by Django 5.2.6 on 2025-11-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0002_charger_scanner_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="power_rating",
            field=models.DecimalField(
                decimal_places=2,
                default=7.5,
                help_text="Power rating in kW",
                max_digits=6,
            ),
        ),
    ]
