# Generated by Django 5.2.6 on 2025-11-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0003_charger_power_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="charger",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
