# Generated by Django 5.2.6 on 2025-11-03 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("host", "0002_charger_scanner_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["charger", "booking_date", "start_time", "end_time"],
                name="bookings_bo_charger_250951_idx",
            ),
        ),
    ]
