# Generated by Django 5.2.6 on 2025-11-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_is_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
