# Generated by Django 5.2.6 on 2025-11-04 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_booking_payment_date"),
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="plug",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="driver.plugtype",
            ),
        ),
    ]
