# Generated by Django 5.2.6 on 2025-11-07 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_plug"),
        ("driver", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="vehicle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="driver.vehicle",
            ),
            preserve_default=False,
        ),
    ]
